ngrok config edit
version: 2
authtoken: 2n2r3fZ19IMjNaqDhj77iMaNFo9_5rvXSLohA3niD1te5NsUf
tunnels:
 my_tunnel_name:
  addr: http://localhost:80

  ngrok start your_tunnel_name

  ngrok start --all

  
